OpenVisualCloud/SVT-VP9

- Build/windows/generate_vs17.bat
- Source/App/EbAppConfig.c
> Fix reading from stdin

- Build/windows/generate_vs17.bat
- gstreamer-plugin/CMakeLists.txt
- gstreamer-plugin/README.md
- gstreamer-plugin/gstsvtvp9enc.c
- gstreamer-plugin/gstsvtvp9enc.h
- gstreamer-plugin/meson.build
> GStreamer plugin

- Source/Lib/Codec/EbEncHandle.c
Modified EbEncHandle.c file to block the non multiple of 8 resolution.
> Block input with non multiple of 8 resolution

- Source/App/EbAppProcessCmd.c
> Fix fps in ivf header

- .travis.yml
Still needs fix for clang etc.
> travis: Port changes from SVT-AV1

- Source/Lib/Codec/EbPacketizationProcess.c
- Source/Lib/Codec/EbPictureDecisionProcess.c
Signed-off-by: Austin Hu <austin.hu@intel.com>
> Don't call exit() directly.

- Source/Lib/ASM_SSE2/x64Macro.asm
- Source/Lib/ASM_SSE2/x64inc.asm
Signed-off-by: Austin Hu <austin.hu@intel.com>
> Don't compile the binaries as executable stack.

- .travis.yml
- Build/linux/build.sh
- CMakeLists.txt
- README.md
- Source/API/EbApi.version
- Source/API/EbExport_List
- Source/API/EbSvtVp9Time.h
- Source/App/EbAppConfig.h
- Source/App/EbAppFifo.c
- Source/App/EbTime.c
- Source/Lib/Codec/CMakeLists.txt
- Source/Lib/Codec/EbDefinitions.h
- Source/Lib/Codec/EbEncHandle.c
- Source/Lib/Codec/EbEncHandle.h
- Source/Lib/Codec/EbUtility.c
Definitely could use more clean up
> StaticLib: Add static library support

- .travis.yml
- Updates Linux build environment to Ubuntu Bionic 18.04
- Update FFmpeg to 4.2 branch
> Travis maintenance: Update Linux build environment, FFmpeg

- CMakeLists.txt
- nasm with some version can't find include statements from cmake
- Port the change from SVT-AV1
> Use yasm if present in PATH

- Config/Sample.cfg
- Docs/svt-vp9_encoder_user_guide.md
- Source/App/EbAppConfig.c
- Source/Lib/Codec/EbPictureDecisionProcess.c
> Fix video corruption for non-multiple-of-8 gop size 

- ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-vp9-with-svt-hevc-av1.patch
- ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch
Ported from AV1 PR #805.
Signed-off-by: Austin Hu <austin.hu@intel.com>
Fixes #73 .
> ffmpeg: fix assert in avcodec_receive_packet

- appveyor.yml
Limits the build to only msvc+debug and release+gcc for PRs to save some time and only pushes artifacts on the master branch to save space since that's the only place we really need it
> Appveyor: Limit to 2 jobs for PR and only push artifacts on master branch

- appveyor.yml
ffmpeg plugin patch can't apply to ffmpeg master for now.
Just run test for ffmpeg 4.2 release branch.
> Only run test with ffmpeg 4.2

- ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-vp9-with-hevc-av1.patch
- ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch
Followed the same idea of PR #80.
> ffmpeg-v4.2: Work around the "Dash-player does not play back..." (#89)

- appveyor.yml
Signed-off-by: Christopher Degawa <ccom@randomderp.com>
> appveyor: Fix pacman failing to install packages

- .gitignore
- Build/windows/build.bat
- Build/windows/generate_vs17.bat
Remove generate_vs17.bat while at it
Closes #93
> build: Add build.bat

- Source/Lib/pkg-config.pc.in
Signed-off-by: Thomas Heijligen <src@posteo.de>
> pkg-config: use CMAKE_INSTALL_FULL for ${prefix}

- appveyor.yml
Will try to move the artifact uploading to github actions if possible
> appveyor: Disable artifact release for now

- ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-vp9-with-hevc-av1.patch
Signed-off-by: Christopher Degawa <ccom@randomderp.com>
> ffmpeg: Rebase combination patch with SVT-AV1 changes

- ffmpeg_plugin/README.md
- ffmpeg_plugin/master-0001-Add-ability-for-ffmpeg-to-run-svt-vp9-with-hevc-av1.patch
- ffmpeg_plugin/master-0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch
- ffmpeg_plugin/n4.2.3-0001-Add-ability-for-ffmpeg-to-run-svt-vp9-with-hevc-av1.patch
- ffmpeg_plugin/n4.2.3-0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch
>  ffmpeg: Add patches for master and n4.2.3 branch

- ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-vp9-with-hevc-av1.patch
- ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch
- ffmpeg_plugin/master-0001-Add-ability-for-ffmpeg-to-run-svt-vp9-with-hevc-av1.patch
- ffmpeg_plugin/master-0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch
- ffmpeg_plugin/n4.2.3-0001-Add-ability-for-ffmpeg-to-run-svt-vp9-with-hevc-av1.patch
- ffmpeg_plugin/n4.2.3-0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch
> ffmpeg: bug fix in eb_receive_packet

- ffmpeg_plugin/master-0001-Add-ability-for-ffmpeg-to-run-svt-vp9-with-hevc-av1.patch
- ffmpeg_plugin/master-0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch
> FFmpeg: Remove -intra_refresh_type from master patches

- ffmpeg_plugin/README.md
- ffmpeg_plugin/master-0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch
> FFmpeg: make master patch compatible with n4.3 branch

- ffmpeg_plugin/master-0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch
Signed-off-by: Christopher Degawa <christopher.degawa@intel.com>
> ffmpeg_plugin: Rebase master patch

- Source/Lib/Codec/EbEncHandle.c
> Add missing default interface values

- ffmpeg_plugin/master-0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch
> ffmpeg: Rebase master branch

- ffmpeg_plugin/master-0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch
> ffmpeg: Rebase master patch

- Source/Lib/ASM_SSE2/subtract_sse2.asm
- Source/Lib/VPX/vp9_encoder.c
- Source/Lib/VPX/vp9_rdopt.c
- Source/Lib/VPX/vpx_dsp_rtcd.h
Signed-off-by: Christopher Degawa <christopher.degawa@intel.com>
> vpx_subtract_block: prefix with svt_ to prevent conflict with libvpx

- Source/Lib/Codec/EbEncDecProcess.c
> Fix artifacts with preset 5
