OpenVisualCloud/SVT-VP9

- README.md
* Adds info about the #svt IRC channel
* Uses smaller headings to save space
* Links to issue tab
> Readme: Add IRC channel, use smaller headings

- appveyor.yml
To prevent OpenVisualCloud/SVT-HEVC#361
> AppVeyor: Only deploy Release build to GitHub releases

- appveyor.yml
Add ffmpeg compiling for release builds
Compress the archives before adding them to artifacts
First builds will be around 30+ minutes for release builds since the ccache cache won't be populated,
Takes around 10 minutes afterwards
The SVT-VP9.tar.xz in the artifacts tab will include the dlls, exe, and a copy of ffmpeg.exe with libsvt_vp9 for release builds, I think this should be fine since we aren't compiling non-free and afaik none of the license is being violated.
The github releases should still be fine
@EwoutH, please check to see if there is anything that needs to be improved or is wrong, I am planning to submit similar changes for SVT-{HEVC,AV1} soon
This should help with the artifact sizes a little bit
> Appveyor: Add debug and release msvc and mingw builds

- ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-vp9-with-svt-hevc-av1.patch
- ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch
- ffmpeg_plugin/README.md
ffmpeg: Worked around the "Too many invisible frames" issue for mkv/webm.
Followed the same idea of PR #28 to change container.
The SVT-VP9 encoder is designed to append 4 one-byte repeated frames
during Packetization, "periodically" determined by generate_rps_info()
in PictureDecision. But the 4 repeated frames are packetized with their
previous invisible frame as one (AVPacket) packet, which can't be parsed
as repeated frames when decoding them.
So temporarily separate the 4 repeated frames during packet writing
for each container (currently mkv/webm).
Signed-off-by: Austin Hu austin.hu@intel.com
Fixes #74 .
> ffmpeg-v4.2: Worked around the "Too many invisible frames" issue for mkv/webm

- ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-vp9-with-hevc-av1.patch
- ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch
Followed the same idea of PR #80.
Fixes #84
> ffmpeg-v4.2: Work around the "Too many invisible frames" issue for mp4

- Source/App/EbAppContext.c
- Source/App/EbAppContext.h
Since nothing is currently using the buffer pool
Matching SVT-HEVC PR: https://github.com/OpenVisualCloud/SVT-HEVC/pull/527
Matching SVT-AV1 PR: OpenVisualCloud/SVT-AV1#1209
> App/EbAppContext.c: Remove unused stream_buffer_pool and allocate_output_buffers

- Config/Sample.cfg
- Docs/svt-vp9_encoder_user_guide.md
- Source/API/EbSvtVp9Enc.h
- Source/App/EbAppConfig.c
- Source/App/EbAppConfig.h
- Source/App/EbAppContext.c
- Source/Lib/Codec/EbDefinitions.h
- Source/Lib/Codec/EbEncHandle.c
- Source/Lib/Codec/EbEncodeContext.c
- Source/Lib/Codec/EbEncodeContext.h
- Source/Lib/Codec/EbPictureControlSet.h
- Source/Lib/Codec/EbPictureDecisionProcess.c
- Source/Lib/Codec/EbResourceCoordinationProcess.c
- Source/Lib/Codec/EbSequenceControlSet.c
- Source/Lib/Codec/EbSequenceControlSet.h
- ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-vp9-with-hevc-av1.patch
- ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch
- gstreamer-plugin/gstsvtvp9enc.c
Removed duplicated check for scene change or intra_period start
Force idr_flag on (VP9 does not appear to support cra in bitstreams)
Signed-off-by: Mark Feldman <mark.feldman@intel.com>
> Removing -irefresh-type option from VP9 encoder

- Source/Lib/Codec/EbThreads.h
On nix systems with mingw-w64, gcc will error out on `Windows.h` since they do not do case insensitive include search
> EbThreads: use lowercase windows.h for case sensitive systems

- Source/Lib/Codec/EbInitialRateControlProcess.c
When for loop termination condition is -1, it is
a big value for unsigned.
Execution of loop continues until runs over the
array range, causing invalid pointer is accessed.
> Fix crash with -intra-period 255

- ffmpeg_plugin/master-0001-Add-ability-for-ffmpeg-to-run-svt-vp9-with-hevc-av1.patch
- ffmpeg_plugin/master-0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch
https://git.videolan.org/?p=ffmpeg.git;a=commitdiff;h=827d6fe73d2f5472c1c2128eb14fab6a4db29032 changed the internal encode API, as as such the ffmpeg plugin needs to be adapted.
Without this change, the plugin will fail to build starting with lavc version 58.93.100
Fixes #118
> ffmpeg: Adapt with new libavcodec internal encode api changes

- Source/Lib/Codec/EbEntropyCodingProcess.c
- Source/Lib/Codec/EbPictureControlSet.h
- Source/Lib/Codec/EbSequenceControlSet.c
Fixed an issue that arose when frame sizes were non standard sized.
(e.g. non multiples of the largest coding unit (lcu) (64x64)).
For the example below the frame size used is 104x64. Encoded frames
showed a visible artifact.  In other cases, the frame could not be
successfully decoded by VQ Analyzer.
Root cause of the problem was in the logic that determined if the
current block to be coded contained a valid block (one which is fully
inside the frame).  If it did not contain a valid block, the current
block would be considered invalid and thus not coded.
The previous logic only checked the current block and blocks at
the next lowest depth for valid blocks.  However for certain sizes
(e.g. 104x64) some blocks require that a lower depth be searched
for valid blocks.
In this example, the …
> Specific Resolution Fix

- Source/Lib/ASM_AVX2/EbNoiseExtractAVX2.c
- Source/Lib/ASM_AVX2/EbNoiseExtractAVX2.h
- Source/Lib/Codec/EbEncDecProcess.c
- Source/Lib/Codec/EbEncHandle.c
- Source/Lib/Codec/EbInitialRateControlProcess.c
- Source/Lib/Codec/EbInitialRateControlProcess.h
- Source/Lib/Codec/EbModeDecisionConfigurationProcess.c
- Source/Lib/Codec/EbMotionEstimation.h
- Source/Lib/Codec/EbMotionEstimationProcess.c
- Source/Lib/Codec/EbPictureAnalysisProcess.c
- Source/Lib/Codec/EbPictureDecisionProcess.c
- Source/Lib/Codec/EbPictureOperators.c
- Source/Lib/Codec/EbPictureOperators.h
- Source/Lib/Codec/EbReferenceObject.c
- Source/Lib/Codec/EbSourceBasedOperationsProcess.c
- Source/Lib/Codec/EbThreads.h
Some conflicts somehow still remain.
Closes https://github.com/OpenVisualCloud/SVT-AV1/issues/73
> Fix more conflicts with SVT-AV1

- CMakeLists.txt
Fixed build with GCC 11 by moving MSVC flags:
```
-- Performing Test C_FLAG_sdl
-- Performing Test C_FLAG_sdl - Failed
-- Performing Test C_FLAG_fstack_protector_strong
-- Performing Test C_FLAG_fstack_protector_strong - Failed
-- Performing Test C_FLAG_msse2
-- Performing Test C_FLAG_msse2 - Failed
-- Performing Test C_FLAG_mssse3
-- Performing Test C_FLAG_mssse3 - Failed
-- Performing Test C_FLAG_msse4_1
-- Performing Test C_FLAG_msse4_1 - Failed
-- Performing Test C_FLAG_mavx2
-- Performing Test C_FLAG_mavx2 - Failed
gcc: warning: /GS: linker input file unused because linking not done
```
Closes #132.
> Fixed build with GCC 11 by moving MSVC flags

- ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch
- ffmpeg_plugin/master-0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch
- ffmpeg_plugin/n4.2.3-0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch
- ffmpeg_plugin/n4.3.1-0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch
In real SVT VP9 use as a part of FFmpeg on multi-socket systems (e.g .Xeon 8260L) there is a strong need  to select the target socket to run encoder on to balance the server load evenly
> ffmpeg patches: target socket selection option added

- ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch
- ffmpeg_plugin/master-0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch
- ffmpeg_plugin/n4.2.3-0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch
- ffmpeg_plugin/n4.3.1-0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch
fixes #147 
validated with mp4/mkv/webm.
> ffmpeg: adjust pts to avoid duplicate frames in mp4 format

- ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch
- ffmpeg_plugin/master-0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch
- ffmpeg_plugin/n4.2.3-0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch
- ffmpeg_plugin/n4.3.1-0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch
There are some issues when muxing svt-vp9 stream to a specific container.
In the previous solution, we do workaround for each container(ivf, mkv/webm, mp4).
This patch re-pack frames when receiving packet to avoid different workaround in each container.
Validated with ivf/webm/mkv/mp4 formats.
Thanks to the contribution from Yandex.
Signed-off-by: Andrei Bich <dronimal@yandex-team.ru>
> ffmpeg: re-pack when receiving packet to avoid mux issues to different formats

- Source/Lib/Codec/EbUtility.c
- Source/Lib/Codec/EbUtility.h
Avoid name conflict on `log2f64` function name from `math.h` system header on Ubuntu 18+:
```
Source/Lib/Codec/EbUtility.h:95:17: error: conflicting types for 'log2f64'
extern uint64_t log2f64(uint64_t x);
^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:133:1: note: previous declaration is here
__MATHCALL (log2,, (_Mdouble_ __x));
^
/usr/include/math.h:273:3: note: expanded from macro '__MATHCALL'
__MATHDECL (_Mdouble_,function,suffix, args)
^
/usr/include/math.h:275:3: note: expanded from macro '__MATHDECL'
__MATHDECL_1(type, function,suffix, args); \
^
/usr/include/math.h:283:15: note: expanded from macro '__MATHDECL_1'
extern type __MATH_PRECNAME(function,suffix) args __THROW
^
/usr/include/math.h:399:34: note: expanded from macro '__MATH_PRECNAME'
^
<scratch space>:301:1: note: …
```
> Avoid name conflict on `log2f64` from `math.h`

- ffmpeg_plugin/master-0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch
@guojiansheng0925 can you check if this patch is correct? I essentially replaced AV_CODEC_CAP_AUTO_THREADS with AV_CODEC_CAP_OTHER_THREADS and filled in .caps_internal with fields from SVT-AV1 since this lib matches close to what SVT-AV1 does
Closes https://github.com/m-ab-s/media-autobuild_suite/issues/2376
> ffmpeg: rebase master branch patch for FF_CODEC_CAP_AUTO_THREADS

- Source/Lib/Codec/EbThreads.c
Current code will erroneously try to cancel thread when failing to create it causing a segfault.
Now uses same scheduling parameter as SVT-AV1.
> EbThreads: Replace thread create function with the one from SVT-AV1

- Source/Lib/Codec/EbComputeSAD.h
- Source/Lib/VPX/intrapred.c
There seemed to be an issue with `d135_predictor()` and `eb_vp9_get_eight_horizontal_search_point_results_32x32_64x64_pu_avx2_intrin()` that was causing a difference between the two asm choices. Additionally, I believe it was causing a run to run issue with `-asm 0`.
Specifically, the issue seemed to be with `eb_vp9_d135_predictor_8x8()`. For this, I just repulled the latest version from libvpx as it seems that it's not an issue there.
For the other, I've just disabled using the avx2 version until it can be investigated further, if ever.
> Fix difference between -asm 0 and -asm 1 output
